### ISSUE TITLE
[Feature] Streaming Report

### ISSUE THREAD

**Issue by elpiel** [Stremio/stremio-web#354]
The streaming report in web is currently not implemented while in Stremio 4 desktop app it is

### TODO
- [x] This would probably require changes in [stremio-core](https://github.com/Stremio/stremio-core)
  - [x] Fetch statistics from the server in `StreamingServer` model, e.g. `http://127.0.0.1:11470/c9f2620b2183b14806f19b51924bc94b004eb1e4/0/stats.json`
  - [x] handle request response in `Player`
  - [x] Make sure to request statistics every X seconds
- [x] Check if requires changes in `core-web` 

Stream model in Stremio 4 - https://github.com/Stremio/stremio-models/blob/df583c7af1761a10b0fc1e0f0d6c339cc8bd28ad/stream.js#L279-L308
Server statistics in enginefs - https://github.com/Stremio/enginefs/blob/ea273765ee52e044f38184232f01d3ec84823da9/enginefs.js#L480
